# SPDX-License-Identifier: MIT
---
- name: Pin DRBD module package version
  when: drbd_install_module_version | length > 0
  ansible.builtin.set_fact:
    drbd_install_packages: >-
      {{ drbd_install_packages
         | reject('equalto', _drbd_module_package)
         | list
         + [drbd_install_pinned_module] }}

- name: Check if DRBD packages need changes
  ansible.builtin.apt:
    name: "{{ drbd_install_packages }}"
    state: "{{ drbd_install_package_state }}"
    allow_downgrade: true
  check_mode: true
  register: _drbd_check
