# SPDX-License-Identifier: MIT
---
- name: Load OS-specific tasks for drbd_install
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "install-{{ ansible_facts['distribution'] | lower }}.yml"
        - "install-{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "{{ role_path }}/tasks"
      skip: true

- name: Open firewall ports for DRBD
  ansible.builtin.include_tasks: open-firewall.yml
  when: drbd_install_firewall_rules | bool

- name: Install DRBD packages
  ansible.builtin.include_tasks: "package-install-{{ ansible_facts['os_family'] | lower }}.yml"

- name: Lock DRBD module package version
  ansible.builtin.include_tasks: "lock-{{ ansible_facts['os_family'] | lower }}.yml"
  when: drbd_install_module_version | length > 0
