# SPDX-License-Identifier: MIT
---
# DRBD uses DKMS, so install headers for all installed kernels.
# proxmox-default-headers: metapackage for PVE kernel headers
# linux-headers-amd64: metapackage for stock Debian kernel headers
# pahole: needed for DKMS builds with BTF-enabled kernels
- name: Queue DRBD pre-req packages (Proxmox VE)
  ansible.builtin.set_fact:
    drbd_install_prereqs: "{{ drbd_install_prereqs + ['proxmox-default-headers', 'pahole'] }}"
  when:
    - ansible_facts['distribution'] | lower == 'debian'
    - ansible_facts | linbit.common.is_pve

- name: Queue DRBD pre-req packages (Debian kernel headers)
  ansible.builtin.set_fact:
    drbd_install_prereqs: "{{ drbd_install_prereqs + ['linux-headers-' + _debian_arch] }}"
  when:
    - ansible_facts['distribution'] | lower == 'debian'
    - "'pve' not in ansible_facts['kernel']"

- name: Queue DRBD pre-req packages (Ubuntu OS)
  ansible.builtin.set_fact:
    drbd_install_prereqs: "{{ drbd_install_prereqs + ['linux-headers-generic'] }}"
  when: ansible_facts['distribution'] | lower == 'ubuntu'
