# SPDX-License-Identifier: MIT
---
- name: Gather OS facts for OS-specific vars
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - min
  when: ansible_facts['os_family'] is not defined

- name: Load os-family variables for drbd_install
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ ansible_facts['os_family'] | lower }}.yml"

- name: Load distribution-specific overrides for drbd_install
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['distribution'] | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true
  when: ansible_facts['distribution'] | lower != ansible_facts['os_family'] | lower

- name: Check if drbdadm is installed
  ansible.builtin.stat:
    path: "{{ _drbd_install_drbdadm_path }}"
  register: _drbd_install_drbdadm_check

- name: Check DRBD kernel module version
  ansible.builtin.slurp:
    src: /sys/module/drbd/version
  register: _drbd_install_module_check
  failed_when: false

- name: Install and configure DRBD
  when:
    - not _drbd_install_drbdadm_check.stat.exists
      or _drbd_install_module_check.content is not defined
      or (_drbd_install_module_check.content | default('') | b64decode | trim) is match('^8\.')
      or drbd_install_module_version | length > 0
      or drbd_install_package_state != 'present'
      or drbd_install_force_reconfigure | bool
  block:
    - name: Unlock DRBD module package version
      ansible.builtin.include_tasks: "unlock-{{ ansible_facts['os_family'] | lower }}.yml"

    - name: Pin DRBD module package version
      ansible.builtin.include_tasks: "pin-version-{{ ansible_facts['os_family'] | lower }}.yml"
      when: drbd_install_module_version | length > 0

    - name: Install DRBD
      ansible.builtin.include_tasks: install-drbd.yml

- name: Gather service facts to check for drbd-graceful-shutdown
  ansible.builtin.service_facts:
  when: drbd_install_mask_shutdown_service | bool

- name: Mask drbd-graceful-shutdown.service
  ansible.builtin.systemd_service:
    name: drbd-graceful-shutdown.service
    masked: true
  when:
    - drbd_install_mask_shutdown_service | bool
    - ansible_facts.services['drbd-graceful-shutdown.service'] is defined

- name: Flush handlers for drbd_install
  ansible.builtin.meta: flush_handlers
