# SPDX-License-Identifier: MIT
---
# tasks file for drbd_install
- name: Load OS-specific variables for drbd_install
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true

- name: Load OS-specific tasks for drbd_install
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "{{ role_path }}/tasks"
      skip: true

- name: Gather service facts
  ansible.builtin.service_facts:

# Use LINSTOR port range 7000-8000
- name: Open firewalld ports for DRBD
  ansible.posix.firewalld:
    port: 7000-8000/tcp
    permanent: true
    immediate: true
    state: enabled
  when:
    - ansible_facts.services['firewalld.service'] is defined
    - ansible_facts.services['firewalld.service'].state == 'running'

# nobest -> true needed if non-RHEL releases lag behind on kernel releases
- name: Install LINBIT DRBD packages (Red Hat OS family)
  ansible.builtin.dnf:
    name: "{{ drbd_install_prereqs + drbd_packages }}"
    state: present
    nobest: true
  when: ansible_facts['os_family'] | lower == 'redhat'

- name: Install LINBIT DRBD packages (All other OS)
  ansible.builtin.package:
    name: "{{ drbd_install_prereqs + drbd_packages }}"
    state: present
  when: ansible_facts['os_family'] | lower != 'redhat'
  notify: restart_multipathd
