# SPDX-License-Identifier: MIT
---
- name: Load OS-specific variables for drbd_install
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true

- name: Check if drbdadm is installed
  ansible.builtin.stat:
    path: "{{ _drbd_install_drbdadm_path }}"
  register: _drbd_install_drbdadm_check

- name: Check DRBD kernel module version
  ansible.builtin.slurp:
    src: /sys/module/drbd/version
  register: _drbd_install_module_check
  failed_when: false

- name: Install and configure DRBD
  when:
    - not _drbd_install_drbdadm_check.stat.exists
      or _drbd_install_module_check is failed
      or (_drbd_install_module_check.content | b64decode | trim) is match('^8\.')
      or drbd_install_module_version | length > 0
      or drbd_install_package_state != 'present'
  block:
    - name: Unlock DRBD module package version
      ansible.builtin.include_tasks: "unlock-{{ ansible_facts['os_family'] | lower }}.yml"

    - name: Pin DRBD module package version
      ansible.builtin.include_tasks: "pin-version-{{ ansible_facts['os_family'] | lower }}.yml"
      when: drbd_install_module_version | length > 0

    - name: Install DRBD
      ansible.builtin.include_tasks: install-drbd.yml
