# SPDX-License-Identifier: MIT
---
- name: Install DRBD packages (APT)
  ansible.builtin.apt:
    name: "{{ (drbd_install_prereqs + drbd_install_packages) | reject('falsy') | list }}"
    state: "{{ drbd_install_package_state }}"
    allow_downgrade: true
  notify: restart_multipathd
