# SPDX-License-Identifier: MIT
---
- name: Install EPEL release package (for DKMS)
  ansible.builtin.dnf:
    name: "{{ drbd_install_epel_package }}"
    state: present

- name: Enable CRB/PowerTools repo (DKMS build deps)
  ansible.builtin.command:
    cmd: "dnf config-manager --set-enabled {{ drbd_install_crb_repo }}"
  changed_when: false

- name: Install kernel headers for DKMS (DNF)
  ansible.builtin.dnf:
    name: "{{ ansible_facts | linbit.common.dkms_kernel_headers }}"
    state: present
    nobest: true
    allow_downgrade: true
