# SPDX-License-Identifier: MIT
---
- name: Check existing zypper locks
  ansible.builtin.command:
    cmd: zypper locks
  register: _zypper_locks
  changed_when: false

- name: Unlock DRBD module package version
  ansible.builtin.command:
    cmd: zypper removelock {{ _drbd_module_package }}
  when: _drbd_module_package in _zypper_locks.stdout
