# SPDX-License-Identifier: MIT
---
- name: Remove version lock for DRBD kernel package (Zypper)
  ansible.builtin.command:
    cmd: zypper removelock {{ _drbd_module_package }}
  changed_when: false
  failed_when: false
