# SPDX-License-Identifier: MIT
---
- name: Remove version lock for DRBD kernel package (APT)
  ansible.builtin.dpkg_selections:
    name: "{{ _drbd_module_package }}"
    selection: install
  changed_when: false
  failed_when: false
