# SPDX-License-Identifier: MIT
---
# defaults file for drbd_install

drbd_install_prereqs: []

drbd_install_package_state: present

drbd_install_force_dkms: false

drbd_install_module_version: ""

drbd_install_version_separator: "="

drbd_install_pinned_module: "{{ _drbd_module_package }}{{ drbd_install_version_separator }}{{ drbd_install_module_version }}*"

drbd_install_packages: []

drbd_install_firewall_rules: true

drbd_install_firewall_ports:
  - { port: '7000-8000', proto: tcp }

drbd_install_force_reconfigure: false
