# SPDX-License-Identifier: MIT
---
# handlers file for drbd_install
- name: Restart multipathd after installing drbd-utils (Ubuntu Focal only)
  ansible.builtin.systemd:
    name: multipathd
    state: restarted
  when:
    - ansible_facts['distribution'] | lower == 'ubuntu'
    - ansible_facts['distribution_release'] | lower == 'focal'
  listen: restart_multipathd
