# SPDX-License-Identifier: MIT
---
drbd_install_packages:
  - drbd-dkms
 # - drbd-ueficert # not in public proxmox repo
  - drbd-utils

_drbd_module_package: drbd-dkms
_drbd_install_drbdadm_path: /usr/sbin/drbdadm
