# SPDX-License-Identifier: MIT
---
_debian_arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' }}"

# Empty default; OS-specific vars files override via include_vars.
_drbd_module_package: ""

# Filtered out by reject('falsy') during install task
_drbd_install_proxy: "{{ 'drbd-proxy' if drbd_install_drbdproxy | bool else '' }}"
