# SPDX-License-Identifier: MIT
---
drbd_install_packages:
  - drbd
  - drbd-utils
  - kmod-drbd

_drbd_module_package: kmod-drbd
_drbd_install_drbdadm_path: /sbin/drbdadm
drbd_install_version_separator: "-"
