# SPDX-License-Identifier: MIT
---
drbd_install_packages:
  - drbd # needs 'zypper in --no-recommends drbd'
  - drbd-kmp-default
  - drbd-ueficert
  - drbd-utils

_drbd_module_package: drbd-kmp-default
_drbd_install_drbdadm_path: /usr/sbin/drbdadm
